#!/bin/bash
#TryHackMe VPN Troubleshooting
#Jan, 2021
#V1.5
#MuirlandOracle

#Define Colours
colour(){
	if [ $# -lt 2 ]; then
		exit 1
	fi	
	case "$1" in
		"green")
			printf "\033[01;32m$2\033[0m\n"
			;;
		"red")
			printf "\033[01;31m$2\033[0m\n"
			;;
		"header")
			printf "\033[0;1;4m$2\033[0m\n"
			;;
		"code")
			printf "\033[01;31;47m$2\033[0m\n"
			;;
		"warning")
			printf "\033[01;93m[Warning!]\033[0m $2\n"
			;;
		"process")
			printf "\033[01;94m$2\033[0m\n"
			;;
		*)
			return 1
			;;
	esac
	if [ $# -eq 3 ]; then
		sleep $3s
	fi
}

fin(){
	printf "\n\n"
	exit 1
}

connect(){
	testSuccess() ( if grep -qio "Initialization Sequence Completed" $ovpnoutput;then return 0; else return 1;fi )
	testCert() ( if grep -qioE "Cannot load inline certificate file|certificate verify failed|cannot load CA" $ovpnoutput;then return 0; else return 1;fi )
	ovpnoutput=$(mktemp)
	openvpn $ovpn </dev/null &>$ovpnoutput &
	colour process "[+] Connecting...." 10
	for i in {1..2};do
		if testSuccess; then
			colour green "[+] Connection Process completed successfully!" 1
			return 1
		elif testCert; then
			killall -9 openvpn &>/dev/null 2>/dev/null
			colour red "[-] Fatal Error: Inline Certificate is invalid" 1
			printf "Please regenerate your VPN config on the access page (https://tryhackme.com/access)\nIf errors persist, change server then regenerate the config.\nIf all else fails, ask for further assistance on the TryHackMe Discord server, subreddit or forums.\n"
			colour red "[-] Exiting" 2
			return 0
		fi
		if [ $i -le 1 ]; then
			colour warning "Connection process is taking longer than expected to complete" 30
		else
			colour red "[-] Failed to connect" 1
			printf "Failure to connect to the VPN can usually be solved by one of the following options:\n"
			printf "	-Regenerating your OpenVPN config on the TryHackMe access page (https://tryhackme.com/access)\n"
			printf "	-Switching servers, then regenerating your OpenVPN config\n"
			printf "	-Checking your system time. If your system time is incorrect then this can cause issues with the authentication process\n"
			printf "If none of these methods work, please ask for further assistance in the TryHackMe Discord server, subreddit or forums.\n"
			colour red "[-] Exiting" 2
			return 0
		fi
	done
}

#Title
title(){
	printf "\n\n\033[0;1;32m"
	cat << "EOF"
	 _____           _   _            _    __  __		
	|_   _| __ _   _| | | | __ _  ___| | _|  \/  | ___
	  | || '__| | | | |_| |/ _` |/ __| |/ / |\/| |/ _ \
	  | || |  | |_| |  _  | (_| | (__|   <| |  | |  __/
	  |_||_|   \__, |_| |_|\__,_|\___|_|\_\_|  |_|\___|
	           |___/

EOF
	printf "\033[0;35m						@MuirlandOracle\033[0m\n\n\n"
}


if [ ! -f /tmp/thm-title ]; then
	title
else
	colour green "[+] Re-running with root permissions" 1
	rm /tmp/thm-title
fi


sleep 1s

#Check that the script is being run with sudo
if [[ $EUID -ne 0 ]]; then
	colour red "[-] Script is being run as a low-privileged user" 1
	read -p "Would you like to run this script with higher privileges automatically (Y/n)? "  choice
	case "$choice" in
		n|N)
			printf "\n\nPlease run the script with the following command:\n"
			colour code "sudo $0" 1
			colour red "[-] Exiting" 2
			fin
			;;
		*)
			touch /tmp/thm-title
			sudo -E $0
			;;
	esac
	fin
fi


#Find the VPN Config
ovpn=$(find . -maxdepth 1 -name "*.ovpn" -print -quit)
if [ ${#ovpn} -eq 0 ]; then
	colour red "[-] Config not found in current directory" 1
	read -ep "Please enter the path to your config: " ovpn
	ovpn=${ovpn/\~/$HOME}
	if [ ${#ovpn} -lt 5 ]; then
		colour red "[-] Invalid File -- Config should be <your-username>.ovpn" 1
		colour red "[-] Exiting" 2
		fin
	elif [ -f $ovpn ] && [ ${ovpn: -5} ==  ".ovpn" ]; then
		colour green "[+] Config Located successfully" 1
	else
		colour red "[-] Config not located" 1
		colour red "[-] Exiting" 2
		fin
	fi
else
	colour process "[i] Using $ovpn file to connect" 1
fi




#Check Internet connectivity
if [ $(ping -c 1 -q 1.1.1.1 >&/dev/null; echo $?)  -gt 0 ]; then
	colour red "[-] You are not connected to the internet" 1
	colour red "[-] Exiting" 2
	fin
else
	colour green "[+] Stable internet connection" 1
fi


#Ensure that Openvpn is installed
if ! dpkg-query -W -f='${Status}' openvpn &>/dev/null; then
	colour red "[-] OpenVPN is not installed" 1
	read -p "Would you like to install OpenVPN automatically (Y/n)? " choice
	case "$choice" in
		n|N)
			printf "\n\nPlease install OpenVPN manually\n"
			colour red "[-] Exiting" 2
			fin
			;;
		*)
			if  ! dpkg-query -W -f='${Status}' apt &>/dev/null; then
				colour red "[-] System doesn't use apt -- please install OpenVPN manually" 1
				colour red "[-] Exiting" 2
				fin
			else
				apt update &>/dev/null && apt install openvpn -y &>/dev/null & pid=$!
				colour process "[+] Installing OpenVPN..."
				while :; do
        			running=$(ps aux | grep $pid | wc -l)
        			if [ $running -eq 1 ]; then
                		break
        			fi
				done
				if dpkg-query -W -f='${Status}' openvpn &>/dev/null; then
					colour green "[+] Installation Process Completed" 1
				else
					colour red "[-] Installation failed. Please try installing OpenVPN manually -- otherwise ask for further assistance in the TryHackMe Discord server, subreddit or forum" 1
					colour red "[-] Exiting" 2
					fin
				fi
			fi
			;;
	esac
else
	colour green "[+] OpenVPN is installed" 1	
fi

#Check that the server the user chose is online

#Grabs the IP from the users ovpn config file and checks if it is up or not
serverIP="$(grep -o '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}' $ovpn)"

if [ $(ping -c 1 -q $serverIP>&/dev/null; echo $?)  -gt 0 ]; then
	colour red "[-] The OpenVPN server seems to be down. Please check manually and/or reach out to the folks on the discord server" 1
	colour red "[-] Exiting" 2
	fin
else
	colour green "[+] OpenVPN server is up" 1
fi

#Check for multivpn
connections=$(ps aux | grep -v "sudo\|grep" | grep -Eo "openvpn .*\.ovpn" | wc -l)
if [ $connections -gt 1 ]; then
	colour red "[-] More than one connection running" 1
	read -p "Would you like the script to attempt to fix this (Y/n)? " choice
	case $choice in
		n|N)
			printf "\n\nPlease run the following command, then reconnect manually:\n"
			colour code "sudo killall -9 openvpn"
			fin
			;;
		*)
			killall -9 openvpn
			colour green "[+] Killed duplicate processes"
			if connect; then
				exit 0
			fi
	esac
else
	colour green "[+] Only one instance of OpenVPN is running" 1
fi

#Final Check
colour process "[+] Confirming connectivity" 1
if [ $(ping -c 1 -q 10\.10\.10\.10 >&/dev/null; echo $?) -eq 0 ];then
	colour green "[+] Connectivity checks completed!" 2
	colour green "[+] You are connected to the TryHackMe Network" 2
	printf "Your TryHackMe IP address is: $(curl -s http://10.10.10.10/whoami)\n\n"
	colour green "Happy Hacking!" 3
else
	colour red "[-] Something went wrong -- please ask for further assistance in the TryHackMe Discord server, subreddit, or forum" 3
fi

printf "\n"
